version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=getit
      - POSTGRES_USER=getituser
      - POSTGRES_PASSWORD=getitsenha  
    ports:
      - 5432:5432