# Generated by Django 3.2.7 on 2021-09-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_tag_name_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tags',
            new_name='tag',
        ),
    ]
