# Generated by Django 3.2.7 on 2021-09-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.tag'),
        ),
    ]
