# Generated by Django 3.2.7 on 2021-09-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ead3a7', max_length=200),
        ),
    ]
